version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openai_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python app.py
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://username:password@db:5432/openai_db
      - OPENAI_API_KEY=sk-your-openai-api-key
    depends_on:
      - db

volumes:
  postgres_data:
